# -*- coding: utf-8 -*-
"""prerna_stage123.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i4y98RqTRo4QjmhfQT46P9lf4fuy7yCL

##Stage1: Basic Calculator
"""

num1 = float(input("enter first number:"))
num2 = float(input("enter second number:"))
operator = input("enter operator (+,-,*,/): ")

if operator == "+":
  result = num1 + num2
  print("result =",result)
elif operator == "-":
  result = num1 - num2
  print("result =",result)
elif operator == "*":
  result = num1 * num2
  print("result =",result)
elif operator == "/":
  if num2 == 0:
    print("error: divison by zero is not allowed")
  else:
    result = num1/num2
    print("result =",result)
else:
  print("invalid operator")

"""## Stage2: Calculator with result check"""

# After result:
# Check if positive
# Negative
# zero

num1 = float(input("enter first number:"))
num2 = float(input("enter second number:"))
operator = input("enter operator (+,-,*,/):")

if operator == "+":
  result = num1 + num2

elif operator == "-":
  result = num1 - num2

elif operator == "*":
  result = num1 * num2

elif operator == "/":
  if num2 == 0:
    print("error: division by zero is not allowed")
    exit()
  else:
    result = num1 / num2

else:
  print("invalid operator")
  exit()

print("result =",result)

# Checking result
if result > 0:
  print("positive")
elif result < 0:
  print("negative")
else:
  print("zero")

"""#Stage3: Student Grade Calculator"""

name = input("enter student name:")

mark1 = float(input("enter marks for subject 1:"))
mark2 = float(input("enter marks for subject 2:"))
mark3 = float(input("enter marks for student 3:"))

total = mark1 + mark2 + mark3
percentage = (total/300)*100


# Grade calculation
if percentage >= 75:
  grade = "A"
elif percentage >= 60:
  grade = "B"
elif percentage >= 40:
  grade = "C"
else:
  grade = "F"

print("\noutput:")
print(name)
print("total:",total,"/300")
print("percentage:",round(percentage,2),"%")
print("grade:",grade)

